AWSTemplateFormatVersion: 2010-09-09

Resources:
  BorderlessHouseMemeber:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderless-house-members"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  TypesOfGarbage:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderless-type-of-garbage"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "GarbageType"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "GarbageType"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ThisWeekGarbageCharge:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderles-this-week-garbage-charge"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ThisWeekGarbageChargeSlack:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderles-this-week-garbage-charge-slack"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  BorderlessMovein:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderless-house-move-in"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  BorderlessMoveout:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "borderless-house-move-out"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
